name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js 
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.6.0'
        registry-url: 'https://npm.pkg.github.com'
     

    - name: (cache) restore
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: Install
      run: npm install

    - name: (coverage) Install
      run: npm install -g c8

    - name: Build
      run: npm run build


    - name: (coverage) Test
      run: c8 --include=src npm test
     
    - name: Set up Git for commit
      run: |
        git config --global user.name "marina-rofael"
        git config --global user.email "rofaelmarina@gmail.com"  
        
    # Increment the version (this bumps patch version by default)
    - name: Increment Version
      run: npm version patch 

      # Commit and push updated package.json
    - name: Commit Changes
      run: |
        git add . 
        git commit -m "chore: bump version"
        git push
        
    - name: Publish to GitHub Packages
      run: npm publish --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN }}  # GitHub token for authentication
          
# - name: (coverage) Report
#       if: matrix.nodejs >= 18
#       run: |
#         c8 report --reporter=text-lcov > coverage.lcov
#         bash <(curl -s https://codecov.io/bash)
#       env:
#         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
